# Generated by Django 6.0 on 2025-12-16 10:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lift',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
